const std = @import("std");

/// Reset the baseband
/// 
/// * OGF: `0x3`
/// * OCF: `0x1`
/// * Opcode: `<<1, 12>>`
/// 
/// Bluetooth Spec v5.2, Vol 4, Part E, section 7.3.1
/// 
/// The HCI_Set_Event_Mask command is used to control which events are generated by the HCI for the Host. If the bit in the Event_Mask is set to a one, then the event associated with that bit will be enabled. For an LE Controller, the “LE Meta event” bit in the event_Mask shall enable or disable all LE events in the LE Meta event (see Section 7.7.65). The event mask allows the Host to control how much it is interrupted.
/// 
/// The Controller shall ignore those bits which are reserved for future use or represent events which it does not support. If the Host sets any of these bits to 1, the Controller shall act as if they were set to 0.
/// 
/// ## Command Parameters
/// Accepts a list of event identifiers as atoms to indicate whether that
/// event should be included in the mask.
/// 
/// see Bluetooth Spec v5.2, Vol 4, Part E, section 7.3.1, Command parameters
/// 
/// ## Return Parameters
/// * `:status` - command status code
pub const SetEventMask = @This();

// Group Code
pub const OGF: u6  = 0x3;
// Command Code
pub const OCF: u10 = 0x1;
// Opcode
pub const OPC: u16 = 0x10C;

// payload length
length: usize,
pub fn init() SetEventMask {
  return .{.length = 3};
}

// fields: 
// * synchronous_connection_changed
// * disconnection_complete
// * return_link_keys
// * link_supervision_timeout_changed
// * simple_pairing_complete
// * keypress_notification
// * encryption_key_refresh_complete
// * hardware_error
// * extended_inquiry_result
// * page_scan_mode_change
// * io_capability_request
// * remote_oob_data_request
// * flush_occurred
// * read_remote_extended_features_complete
// * link_key_notification
// * data_buffer_overflow
// * connection_complete
// * authentication_complete
// * synchronous_connection_complete
// * sniff_subrating
// * master_link_key_complete
// * enhanced_flush_complete
// * user_confirmation_request
// * io_capability_response
// * connection_packet_type_changed
// * read_clock_offset_complete
// * remote_name_request_complete
// * qos_setup_complete
// * qos_violation
// * read_remote_supported_features_complete
// * le_meta
// * loopback_command
// * link_key_request
// * remote_host_supported_features_notification
// * read_remote_version_information_complete
// * change_connection_link_key_complete
// * user_passkey_request
// * inquiry_result
// * inquiry_resultwith_rssi
// * flow_specification_complete
// * inquiry_complete
// * user_passkey_notification
// * role_change
// * max_slots_change
// * encryption_change
// * pin_code_request
// * page_scan_repetition_mode_change
// * mode_change
// * connection_request

// encode from a struct
pub fn encode(self: SetEventMask, allocator: std.mem.Allocator) ![]u8 {
  var command = try allocator.alloc(u8, self.length);
  errdefer allocator.free(command);
  command[0] = OCF;
  command[1] = OGF << 2;
  command[2] = 0;
  // TODO: implement encoding SetEventMask

  return command;
}

// decode from a binary
pub fn decode(payload: []u8) SetEventMask {
  std.debug.assert(payload[0] == OCF);
  std.debug.assert(payload[1] == OGF >> 2);
  return .{.length = payload.len};
}

test "SetEventMask decode" {
  var payload = [_]u8 {OCF, OGF >> 2, 0};
  const decoded = SetEventMask.decode(&payload);
  _ = decoded;
  try std.testing.expect(false);
  @panic("test not implemented yet");
}

test "SetEventMask encode" {
  const set_event_mask = .{.length = 3};
  const encoded = try SetEventMask.encode(set_event_mask, std.testing.allocator);
  defer std.testing.allocator.free(encoded);
  try std.testing.expect(encoded[0] == OCF);
  try std.testing.expect(encoded[1] == OGF >> 2);
  try std.testing.expect(false);
  @panic("test not implemented yet");
}
