name: Unit Tests

on:
  push:
    #

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: 
      image: kcov/kcov
      options: --security-opt seccomp=unconfined
    timeout-minutes: 15
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y git build-essential curl

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.0.1

      - name: Run Tests
        id: test
        shell: bash
        run: zig build test -Dcoverage

      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} -s kcov-output

